name: match_sorter
description: A dart adaptation of the match-sorter package for javascript
version: 0.2.0
homepage: https://github.com/decafdevs/match-sorter

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  diacritic: ^0.1.3
  collection: ^1.17.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
